# DNB Presentation Generator - OpenAPI Specification

## Overview

This document describes the REST API for the DNB Presentation Generator, an enterprise-grade text-to-presentation generation service designed specifically for banking environments.

**Base URL**: `https://api.presentations.dnb.no/api/v1`  
**Version**: 1.0.0  
**Contact**: devops@dnb.no

## Authentication

All API endpoints require authentication using Azure AD Bearer tokens:

```
Authorization: Bearer <azure_ad_token>
```

## Rate Limiting

- **Default**: 100 requests per minute per user
- **Generation**: 10 requests per minute per user
- **Upload**: 20 requests per minute per user
- **Export**: 30 requests per minute per user

## Core Endpoints

### Health Check

#### GET /health
Basic health check endpoint.

**Response**: 200 OK
```json
{
  "status": "healthy",
  "timestamp": "2024-01-01T12:00:00Z",
  "version": "1.0.0",
  "environment": "production",
  "services": {
    "database": "healthy",
    "cache": "healthy",
    "azure_openai": "healthy",
    "storage": "healthy"
  }
}
```

### Authentication

#### POST /auth/login
Authenticate user with Azure AD.

**Request Body**:
```json
{
  "username": "user@dnb.no",
  "password": "password"
}
```

**Response**: 200 OK
```json
{
  "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...",
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9...",
  "token_type": "bearer",
  "expires_in": 3600
}
```

### Document Upload

#### POST /documents/upload
Upload and process a source document.

**Request**: Multipart form data
- `file`: Document file (PDF, DOCX, TXT, MD)
- `extract_images`: boolean (optional, default: false)
- `detect_pii`: boolean (optional, default: true)

**Response**: 201 Created
```json
{
  "success": true,
  "message": "Document uploaded and processed successfully",
  "data": {
    "id": "doc_123456789",
    "filename": "quarterly_report.pdf",
    "file_size": 2048576,
    "mime_type": "application/pdf",
    "document_type": "pdf",
    "pii_detected": ["email", "phone"],
    "processing_stats": {
      "pages": 15,
      "words": 3500,
      "processing_time": 2.5
    },
    "created_at": "2024-01-01T12:00:00Z"
  }
}
```

### Presentation Generation

#### POST /generate/presentation
Generate a presentation from a source document.

**Request Body**:
```json
{
  "source_document_id": "doc_123456789",
  "metadata": {
    "title": "Q4 Financial Results",
    "description": "Quarterly financial performance presentation",
    "template": "corporate",
    "author": "John Doe",
    "tags": ["finance", "quarterly", "results"]
  },
  "generation_options": {
    "max_slides": 15,
    "include_charts": true,
    "include_images": true,
    "target_audience": "board_of_directors",
    "compliance_level": "strict"
  }
}
```

**Response**: 202 Accepted
```json
{
  "success": true,
  "message": "Presentation generation started",
  "data": {
    "presentation_id": "pres_987654321",
    "job_id": "job_456789123",
    "status": "pending",
    "estimated_completion": "2024-01-01T12:01:00Z",
    "status_url": "/api/v1/presentations/pres_987654321/status"
  }
}
```

#### GET /generate/status/{job_id}
Get generation job status.

**Response**: 200 OK
```json
{
  "success": true,
  "data": {
    "job_id": "job_456789123",
    "status": "running",
    "progress": 65,
    "current_step": "content_generation",
    "completed_steps": ["planning", "research"],
    "estimated_completion": "2024-01-01T12:01:30Z",
    "messages": [
      "Presentation plan created successfully",
      "Content research completed",
      "Generating slide content..."
    ]
  }
}
```

### Presentation Management

#### GET /presentations
List user's presentations.

**Query Parameters**:
- `page`: Page number (default: 1)
- `per_page`: Items per page (default: 20, max: 100)
- `status`: Filter by status (pending, completed, failed)
- `template`: Filter by template
- `sort`: Sort field (created_at, updated_at, title)
- `order`: Sort order (asc, desc)

**Response**: 200 OK
```json
{
  "success": true,
  "data": [
    {
      "id": "pres_987654321",
      "metadata": {
        "title": "Q4 Financial Results",
        "description": "Quarterly financial performance presentation",
        "template": "corporate",
        "author": "John Doe",
        "tags": ["finance", "quarterly"]
      },
      "status": "completed",
      "slide_count": 12,
      "created_at": "2024-01-01T12:00:00Z",
      "updated_at": "2024-01-01T12:02:30Z",
      "export_urls": {
        "pptx": "/api/v1/presentations/pres_987654321/export/pptx",
        "pdf": "/api/v1/presentations/pres_987654321/export/pdf"
      }
    }
  ],
  "total": 45,
  "page": 1,
  "per_page": 20,
  "pages": 3
}
```

#### GET /presentations/{presentation_id}
Get presentation details.

**Response**: 200 OK
```json
{
  "success": true,
  "data": {
    "id": "pres_987654321",
    "metadata": {
      "title": "Q4 Financial Results",
      "description": "Quarterly financial performance presentation",
      "template": "corporate",
      "author": "John Doe",
      "company": "DNB Bank ASA",
      "tags": ["finance", "quarterly"]
    },
    "status": "completed",
    "slides": [
      {
        "id": "slide_111",
        "slide_number": 1,
        "type": "title",
        "content": {
          "title": "Q4 Financial Results",
          "content": ["DNB Bank ASA", "Q4 2024"],
          "speaker_notes": "Welcome to our quarterly results presentation"
        }
      },
      {
        "id": "slide_222", 
        "slide_number": 2,
        "type": "content",
        "content": {
          "title": "Executive Summary",
          "content": [
            "Strong performance across all business units",
            "Revenue growth of 15% year-over-year",
            "Positive outlook for 2025"
          ],
          "speaker_notes": "Highlight key achievements and growth metrics"
        }
      }
    ],
    "generation_stats": {
      "total_slides": 12,
      "generation_time": 28.5,
      "agent_execution_times": {
        "planner": 3.2,
        "research": 5.1,
        "content": 12.8,
        "qa_compliance": 4.7,
        "export": 2.7
      }
    },
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-01-01T12:02:30Z"
  }
}
```

### Export

#### POST /presentations/{presentation_id}/export
Export presentation to specified format.

**Request Body**:
```json
{
  "format": "pptx",
  "options": {
    "include_speaker_notes": true,
    "include_metadata": false,
    "template_customizations": {
      "theme": "dnb_corporate",
      "font_size": "large"
    }
  }
}
```

**Response**: 202 Accepted
```json
{
  "success": true,
  "message": "Export started",
  "data": {
    "export_id": "exp_123456789",
    "format": "pptx",
    "status": "processing",
    "download_url": null,
    "estimated_completion": "2024-01-01T12:03:00Z"
  }
}
```

#### GET /presentations/{presentation_id}/export/{export_id}
Get export status and download link.

**Response**: 200 OK
```json
{
  "success": true,
  "data": {
    "export_id": "exp_123456789",
    "format": "pptx",
    "status": "completed",
    "download_url": "https://storage.dnb.no/exports/pres_987654321_exp_123456789.pptx?token=...",
    "file_size": 2048576,
    "expires_at": "2024-01-02T12:00:00Z",
    "created_at": "2024-01-01T12:02:45Z"
  }
}
```

### Assets

#### GET /assets/templates
List available presentation templates.

**Response**: 200 OK
```json
{
  "success": true,
  "data": [
    {
      "id": "corporate",
      "name": "Corporate Template",
      "description": "Standard corporate presentation template",
      "preview_url": "/assets/templates/corporate/preview.png",
      "supports_charts": true,
      "supports_images": true,
      "max_slides": 25
    },
    {
      "id": "executive",
      "name": "Executive Summary Template", 
      "description": "Executive-level presentation template",
      "preview_url": "/assets/templates/executive/preview.png",
      "supports_charts": true,
      "supports_images": false,
      "max_slides": 15
    }
  ]
}
```

#### GET /assets/images
Search corporate image library.

**Query Parameters**:
- `query`: Search term
- `category`: Image category (logos, icons, backgrounds)
- `size`: Image size filter
- `page`: Page number

**Response**: 200 OK
```json
{
  "success": true,
  "data": [
    {
      "id": "img_123",
      "filename": "dnb_logo_primary.png",
      "category": "logos",
      "size": "1024x512",
      "file_size": 45632,
      "url": "/assets/images/img_123",
      "alt_text": "DNB Bank primary logo",
      "usage_rights": "internal_only"
    }
  ],
  "total": 156,
  "page": 1,
  "per_page": 20
}
```

## Error Responses

All error responses follow a consistent format:

```json
{
  "success": false,
  "message": "Error description",
  "error_code": "ERROR_CODE",
  "details": {
    "field": "Additional error details"
  }
}
```

### Common Error Codes

- `INVALID_REQUEST`: Malformed request body or parameters
- `AUTHENTICATION_REQUIRED`: Missing or invalid authentication token
- `INSUFFICIENT_PERMISSIONS`: User lacks required permissions
- `RESOURCE_NOT_FOUND`: Requested resource doesn't exist
- `RATE_LIMIT_EXCEEDED`: Too many requests
- `FILE_TOO_LARGE`: Uploaded file exceeds size limit
- `UNSUPPORTED_FILE_TYPE`: File type not supported
- `PII_DETECTED`: Personal information detected in content
- `CONTENT_SAFETY_VIOLATION`: Content violates safety guidelines
- `GENERATION_FAILED`: Presentation generation failed
- `EXPORT_FAILED`: Export operation failed
- `QUOTA_EXCEEDED`: User quota exceeded
- `SERVICE_UNAVAILABLE`: External service unavailable

## Webhooks

The API supports webhook notifications for long-running operations:

#### POST /webhooks/register
Register a webhook URL.

**Request Body**:
```json
{
  "url": "https://your-app.com/webhooks/dnb-presentations",
  "events": ["generation.completed", "export.completed"],
  "secret": "webhook_secret_key"
}
```

### Webhook Events

- `generation.started`: Presentation generation started
- `generation.completed`: Presentation generation completed
- `generation.failed`: Presentation generation failed
- `export.completed`: Export completed
- `export.failed`: Export failed

### Webhook Payload

```json
{
  "event": "generation.completed",
  "timestamp": "2024-01-01T12:02:30Z",
  "data": {
    "presentation_id": "pres_987654321",
    "user_id": "user_123",
    "status": "completed",
    "generation_time": 28.5
  }
}
```

## SDK Examples

### Python SDK

```python
from dnb_presentations import DNBPresentationsClient

client = DNBPresentationsClient(
    base_url="https://api.presentations.dnb.no",
    auth_token="your_azure_ad_token"
)

# Upload document
document = client.documents.upload("quarterly_report.pdf")

# Generate presentation
presentation = client.presentations.generate(
    source_document_id=document.id,
    title="Q4 Results",
    template="corporate"
)

# Wait for completion
client.presentations.wait_for_completion(presentation.id)

# Export to PowerPoint
export = client.presentations.export(presentation.id, format="pptx")
export.download("q4_results.pptx")
```

### cURL Examples

```bash
# Upload document
curl -X POST https://api.presentations.dnb.no/api/v1/documents/upload \
  -H "Authorization: Bearer $TOKEN" \
  -F "file=@quarterly_report.pdf" \
  -F "detect_pii=true"

# Generate presentation
curl -X POST https://api.presentations.dnb.no/api/v1/generate/presentation \
  -H "Authorization: Bearer $TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "source_document_id": "doc_123456789",
    "metadata": {
      "title": "Q4 Results",
      "template": "corporate"
    }
  }'

# Check status
curl -X GET https://api.presentations.dnb.no/api/v1/presentations/pres_987654321/status \
  -H "Authorization: Bearer $TOKEN"
```

## Compliance & Security

- **Data Protection**: All data encrypted in transit (TLS 1.3) and at rest (AES-256)
- **Access Control**: Role-based access control with Azure AD integration
- **Audit Logging**: Complete audit trail for all operations
- **PII Detection**: Automatic detection and redaction of personal information
- **Content Safety**: Built-in content filtering and safety checks
- **Data Residency**: EU-only data processing and storage

## Support

- **Documentation**: https://docs.presentations.dnb.no
- **Support Email**: presentations-support@dnb.no
- **Status Page**: https://status.presentations.dnb.no
- **SLA**: 99.9% uptime with 4-hour response time for critical issues
